version: '3.9'

services:
  nodejs-server:
    container_name: stub-server
    build: .
    ports:
      - 49160:8080
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 49170:8080
    volumes: 
      - ./gen/out/openapi/openapi.json:/openapi.json
    environment: 
      SWAGGER_JSON: /openapi.json
